apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgCdUk509dKkh7Vv8payD4gA5dXvkfi+39aEikTTxIV71Mknaaw/z3vOp/Wh/2YtXJa0Y56AILdi7r1AR/HZOBIVY4TkUbbUH/4Kb6GGy/paH7cTuLHiTTmk0u+j42xXFpmtCmfJFY+c3ql8+cl62pAIn8BnP5S4g+BsiYAE2b7saq6CEY9llxvpAa61X5rAMGtsy+T6sDra1F7z8U5H0UXWeQ2vBHa4M8t/z/ZkWawjIScQhMH2tMaGFsWtfQ64GB4O/V2i26TMsvhCF/8fXVMWZjn8V2qb7BlJIcwyATBnfYFW5AxZN1P53RezgqOjWHdF/dM4JaRrTtBYqD0GvhHJwcJUU0j3qHarrd505/9srE5Zl8aqtfdfI3wuCQgLTuxife29vGyYuqWrKlUus4cU649nYzkkBWyoDBuUEkQB4wDRxU6n8AHpjSsWSTS3xxWXkv7g0cdXb2tstxKOLe/KLFgBndWa95royugImG2w5YiMFEVIDYKagVqr9R6+xKqh7dtWViIn1ZKwMRKvtaYENzmavUvA+rhJojCmdx953Mx0Q7i3A1cc+WcXfRKs0FdosYxGqMCiJlxE2K8/rH5SdA3xBCakmlvafAHv4m3kFhPjp94/W1cSK+YYylwVcjUnKBLwgoVt/a5hoiBiRASL3Tt/KYygYAPbv2imJrTsOFmRSvdUAibdhi8gBQ14phH6aOSmPjFKHhJBcWnf9nb84ENzMIdvMKZfiw0MGO7cQWFSaCjjIXn9
    username: AgBKbYWWIPygE9uskqARfQfNFBB3Er5sQma64N9aQPTpJ58HgtUDuUCQnDYqilt18WrOEQDy3aDe0I9Tcs1doeSA46chzuDz7gxWu0SzfRorbONM6Q+CVsTfP1iDTwvuKeOw6azIRIr5WB3Jc8krfYU7zmG0hpGQx84K+MGPF1HCHjQCqa36L6vMvVtttuxgrykCbxwZ8tVcVq/zpRLFNZPmwfz8IfTO7Sa4mLGNVAvOAP0ba28xdGI+WK9hWo0YMpnG9huzivkmn2fPuXGj5sK3ZojggRAMcqyD8QVOvUXo53bJ7eH9hT4TT0gm4egFgicSIq/oNEWvq5A6gSFsD9qi4b5nnZNTqSlQrzuIdfD9Kfe6jjtuMsEra/6Je+hBp7RxByvhysS4n3cB4XYHE/R+MKHqS+O+PaeMzamrQPlkPqRjrQczA2ZTNHezZn/Jnph5zr8Hn5Tzt8ePYcGtnUQY/qtD4xTHQOGKzYsyTa2xCrcnZeJTmgEs4+LkfWXN+XCdl5MYJGyhqF0iNd54aIR7l55/cSvtcFpsgFRv4qtJZR0+18lGK42PxjqrEWeXwElF8IxQH04cUSfahma/sJUN0Y7+xga1+vuEc5IZ+Uetpx37xvweIFwRIfW5D2Nre9aYdcQK+wsj1INXbrJI1jLEubO+Tmi/pKTuYzvwOZhdLAzXl7cQvpRX5X/D7QzVmRd5mjE0fuYkJGBBfZ8=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

