apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCOwjoJJyJjp7N/IMPYYcJS7O11D4mxYVPJXB6q6jpvQmcTTQxcqH/RZ0r9nUXT6AF0QJIvVbumoSO9q/CGpKuLWbaecjaNO0wVoOvN3G3zyRCztjfke6q3N7F/e08JcZjEt8oQH5gWSMvu6B9cTgdWvI0yCNzFLjeEJlraCJKhZS2cw00G9AZGKWLRYuR0ct6Qramx19MfxMlaXHgpwY0JXPIFUjnG2JTDALE8wz1vyIw0u/ZgQKo+o0Op3iAiGry9+FbGAIt4z9Zno3yVSmrMOuM7KQOfX0+9BNGq8ENHOXUuS8nIcnfKE4j/3c4krxQuAQnXE4vHOtDQ3pRWO8jHa1OgxdhEnGE3gmE81hdREY3IveMjm6m+zK3YR4kRxsWpweHmFUlWH5+GGuOKKO5cTXKdVSvth0y0buxn4uU8oCEWLWheQf5CU8zg4u79eTE24zMMxmf39jAGvkmyMS1P3CuN16cE4Ik3qiv7RmYVC7s96H81XUT2a8drfmHXEKhWzfLwVTQpLcuYIkITJepZtEgAmqpb3hdRR1J+H+Pq4GcGeV6CoRxis2JedrrMaPoksm1ouXAC6ZlcG/3UwOObfB6wRnySVput9VjByVMwB/8W2eDksEkM0U+J9q0NpSNWr2F+dm0F9yL1lm0LtBphTudnXAPyX09nNaBnAzAYGxUiXcKxUsXpwnlfGLaeJgnWPbQ0guxLmVaNeXLNkZYkfdT81Ftpc0zQ3J7OlaR28AHvKw2/zcNIhR8WQpcTzZ3VsUjyQB4ERUenYk+9qyAocwXk6mLY+lBZOIAw36mv5kslkSYAHcGaLzi9l1Pfi3Ej2pzx4PfpUdI0zbK8MZRRuj5TdVlqg1dChJ2x4u3o/RUYTTVVnDGmovN2UN7xCfEKFz667aCtopHW1F4ZW2IHntNvf80XrUA/ayGGRR/kZOXGMg595BvK17Ur+O2kKgo=
    IBM_ENTITLED_REGISTRY_USER: AgBQCgLPEumqHTDYpTxPwmy8auWNNX+0teTV8S06R+XI6dyouk97RHYzvJsNURd6hO5kSpgPbMewGEoda1wFCxl1yGsuf18A+0gEeI1+pMK4HGFYHM/KjpcakkJbRT63qLBSHlLUfqpvgcg+8iD42Plkoe/sYSGGzEGXfVbKT42iSUPx76bJuArXHVYd5Ve2xyI8f5XbuMfvu2YLP5JbQN/2Cb94XUjl9O72MgyIm5ePcIVAIduJ+J5rOKtLWV9OeJqJGKNn4Echrl6EOxaB9yAfGLW8bEzb7UPhQ/M+fYR2AiKPiQUZAGair8nZoImn87LLt9ifjyjqX78lHC33TZUHq1jeRq6h0nstRglUBNthxEkdpKyTDIAMqncVLSAqiZ4rRwooBtLP4mQF6Kn6sygGpbr5Rwxhy02GvPU0kRtkzIix7W7NERSlhWRJokGYZgd07z9nOATNBwKg6rG4JGnR7ckxNzZjydInM1krgYTPY09x7EVz0NCAMkKmB+D85LfyrmBFVoL7swRYalwZVKY2/zrR6hpmfFclS/CkM1KvfEP7IlQHmSSVID3IOLtMeNK6ION584Z4WlCM4zUvZeD8I7VW2kaVMye+1xK7O1MCUoCZfKxvQ2vMDTQzYFwokQq8S1aKm84bLQ6CM9lr1yKKf5juEd4YEguPRQIi4yeAxZBN3RqgmHUKkg3ATbNVPnS9JA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

